#!/bin/bash

for ((i=2;i<256;i++))
do
    ifconfig lo0 alias 127.0.0.$i up
done

for ((i=2;i<256;i++))
do
    ifconfig lo0 alias 127.0.1.$i up
done

for ((i=2;i<256;i++))
do
    ifconfig lo0 alias 127.0.10.$i up
done
